(** Utility for parsing symbolic expressions.

    This helper module separates parsing logic to avoid dependency cycles between the core library
    modules and the parser generated by Menhir.
*)

(** [parse_scalar s] parses a string into a scalar symbolic expression.

    Uses [Lexer] and [Parser] to process the input string.

    @param s The mathematical expression string (e.g., "mu * S").
    @return The resulting scalar expression AST.
    @raise Failure if parsing fails.
*)
val parse_scalar : string -> Expr.scalar Expr.t
